version: '3.3'
services:
  jenkins:
    container_name: jenkins_labs
    image: legendarioj4r/jenkins:latest

    # build:
    #   context: .
    #   dockerfile: Dockerfile
    privileged: true
    user: root
    ports:
      - 80:8080
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
